---
- name: Ansible Demo
  hosts: all
  become: true

  tasks:
    - name: Install nginx latest version
      yum:
        name: nginx
        state: latest

    - name: Start nginx
      service:
        name: nginx
        state: started
