---
- name: Ansible Demo
  hosts: all
  become: true

  tasks:
    - name: "Uncomment ModLoad imudp"
      command: "sudo sed '/$ModLoad imudp/s/^#//' -i /etc/rsyslog.conf"

    - name: "Uncomment UDPServerRun"
      command: "sudo sed '/$UDPServerRun 514/s/^#//' -i /etc/rsyslog.conf"

    - name: "Appending IP"
      shell: "echo 'auth.*,authpriv.* @10.110.128.43'>> /etc/rsyslog.conf"
  
    - name: "restart rsyslog service"
      service:
        name: rsyslog
        state: restarted
